### ISSUE TITLE
How to check for existence inside an array in JSONB

### ISSUE THREAD

**Issue by noctivityinc** [palkan/pgrel#16]
Say you have this JSON stored in a field called ```metadata``` on the ```Profile``` table:
```
{
   allergies: ['latex','treenuts'],
   address: {
       state: 'CA'
   }
}
```

How would you search all Profile records for someone who lives in California and is allergic to latex?

In plain AR I believe I would do this:

```
Profile.where("metadata -> 'allergies' ? :allergy",{allergy: 'latex'}).where("metadata -> 'address' ->> 'state' = :state",{state: 'CA'})
```

**Comment by palkan** [comment]
The second condition (more precisely, its equivalent) could be constructed as: `Profile.where.store(:metadata).path(:address, :state, 'CA')`.

The first one is not possible at the moment; the support for such queries is discussed here: https://github.com/palkan/pgrel/issues/15
